# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sls-go-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-2'}

package:
  patterns:
    - '!./**'
    - ./api/bin/**
  individually: true

functions:
  hello:
    handler: api/bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: api/bin/world
    events:
      - httpApi:
          path: /world
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true